/*IF
	See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
 	EquipMostDamagingMelee()
 	AttackReevaluate(LastSeenBy(Myself),30)
	// MoveToObject(NearestEnemyOf(Myself))

 	Continue()
END

IF
	AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
  	Attack(LastAttackerOf(Myself))
  	Continue()
END*/
IF
	See(NearestEnemyOf(Myself))
	InWeaponRange(LastSeenBy(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	AttackedBy([ANYONE],DEFAULT)
	InWeaponRange(LastAttackerOf(Myself))
THEN
	RESPONSE #100
		Attack(LastAttackerOf(Myself))
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END
